export const UPDATE_CHARACTER_LIST = '@characters/UPDATE_CHARACTER_LIST';
export const UPDATE_CHARACTER_LOADING = '@characters/UPDATE_CHARACTER_LOADING';
export const UPDATE_CHARACTER_ITEM = '@characters/UPDATE_CHARACTER_ITEM';
