export const UPDATE_EPISODES_LIST = '@episodes/UPDATE_EPISODES_LIST';
export const UPDATE_EPISODES_LOADING = '@episodes/UPDATE_EPISODES_LOADING';
export const UPDATE_EPISODES_ITEM = '@episodes/UPDATE_EPISODES_ITEM';
