export const UPDATE_LOCATIONS_LIST = '@episodes/UPDATE_LOCATIONS_LIST';
export const UPDATE_LOCATIONS_LOADING = '@episodes/UPDATE_LOCATIONS_LOADING';
export const UPDATE_LOCATIONS_ITEM = '@episodes/UPDATE_LOCATIONS_ITEM';
